version: "3"
services:
  ros2:
    build:
      context: ../../
      dockerfile: .devcontainer/ROS2/Dockerfile
    container_name: ros2
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /dev/shm/:/dev/shm
      - ../../:/root/ros2_ws/
      - ../../.data/.rviz2:/root/.rviz2/
      - ../../.data/.rqt:/root/.rqt/
      - /dev/bus/usb/:/dev/bus/usb/
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
    working_dir: /root/ros2_ws
    command: "sleep infinity"
