/twig_teleop_direct:
  ros__parameters:
    joy:
      axis:
        gripper: 3
        shoulder: 1
        wrist: 0
      button:
        activate_servos: 9
        deactivate_servos: 8
        deadmanswitch: 7
      deadband: 0.2
    shoulder_max_speed: 0.33
    wrist_max_speed: 0.33
    gripper_max_speed: -0.33