/twig_teleop_direct:
  ros__parameters:
    joy:
      axis:
        gripper: 0
        shoulder: 1
        wrist: 3
      button:
        activate_servos: 8
        deactivate_servos: 9
        deadmanswitch: 7
      deadband: 0.2
    shoulder_max_speed: 0.33
    wrist_max_speed: 0.33
    gripper_max_speed: -0.33