# https://index.ros.org/r/teleop_twist_joy/

teleop_twist_joy_node:
  ros__parameters:
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5
    scale_angular:
      yaw: 0.4

    axis_linear:
      x: 1 # left_stick_y
    axis_angular:
      yaw: 0 # left_stick_x
    enable_button: 5  # right_trigger
    enable_turbo_button: 7  # right_bumper
