/twig_hardware_node:
  ros__parameters:
    auto_acknowledge_hardware_reboot: true
    command_timeout: 2000
    hardware_config:
      connection_timeout: 2000
      encoder_min_magnitude: 10
      max_current: 1.0
      max_current_cooldown_duration: 0
      max_current_duration: 1000
    joint_config:
      gripper:
        limits:
          max: 6.141592653589793
          min: -6.141592653589793
        offset: 0.0
      shoulder:
        limits:
          max: 6.0
          min: -6.0
        offset: 2.1
      wrist:
        offset: 1.0
    publish_rate: 50
    push_rate: 50